server:
    port: 8082
#单数据源
spring:
  #redis
  redis:
    database: 0
    host: 39.108.
    port: 6379
    password: J
    pool:
      max-active: 8
    timeout: 0
  session:
    store-type: none
  ## Dubbo 服务提供者配置
  dubbo:
    application:
      name: demo-consumer
    base-package: com.tv.service  # dubbo服务调用者所在的包
    registry:
      address: 127.0.0.1                   # zookeeper注册中心的地址
      port: 2181                           # zookeeper注册中心的端口
    consumer:
      timeout: 1000
      check: true                          # 服务启动时检查被调用服务是否可用
      retries: 2
  ##Caffeine Cache
  cache:
      type: CAFFEINE
      cache-names:
        - localCache
      caffeine:
        spec: maximumSize=500,expireAfterWrite=5s
